# frozen_string_literal: true

module CONSTANTS
  THREAD_COUNT = (ENV['RAILS_THREAD_COUNT'] || '4').to_i
end

module RDBMS
  SERIAL_PRIMARY_KEY = 'SERIAL PRIMARY KEY'
  TIMESTAMP_WITH_TIMEZOE = 'timestamp with time zone'
end

module AWS
  ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
  SECRET_ACCESS_KEY = ENV['AWS_SECRET_ACCESS_KEY']
  REGION = ENV['AWS_REGION']
  ACCESS_LOG_BUCKET = ENV['AWS_ACCESS_LOG_BUCKET']
end
